remote_user: ansible
iscsi_iqn_name: iqn.2222-12.ru.trololo
iscsi_target_name: storage.target00
iscsi_host: 10.0.1.17
iscsi_disk: /dev/vdb
multipath_disk: /dev/sda
static_dir: /mnt/static

### PCS
pcs_hacluster_password: "ao3oosaivo8aicieng0Ozex8roo4Ua"

### MYSQL
pxc_cluster_lb_host: "10.0.1.50"
pxc_cluster_lb_port: "6033"
pxc_cluster_name: "pxc-cluster"
pxc_root_password: "wnIAh7wOVaRZgLTqyAoBXZQfmueqBj"
pxc_proxysql_username: "proxysql"
pxc_proxysql_password: "mrBq2lYaboSDXhNcRfNqfA2auM3jmz"
cms_name: "wordpress"
cms_database: "wordpress"
cms_username: "wordpress"
cms_password: "dMn3T5eXqehwOpAiNHaDa4Jhe7WHi3"

### POSTGRESQL
patroni_cluster_lb: "10.0.1.51"
patroni_scope: "patroni-cluster"
postgresql_replicator_pass: "i6hfu3Fb58K28akjUOpP"
postgresql_postgres_pass: "3ZsyNJmDwbxTOEA6oycy"
postgresql_data_dir: /data

### ETCD
etcd_initial_cluster_token: "zw7A38sTGFrF7bTycjvB"

### ELASTIC
elk_cluster_name: elasticsearch-cluster
elk_user_elastic: elastic
elk_pass_elastic: "PHcrTauR5brSxAqiKOJx"
elk_data_dir: /data

frontends:


backends:


mysqls:


postgresqls:


elasticsearchs:
  - host: 10.0.1.27
    name: elasticsearch-1
  - host: 10.0.1.13
    name: elasticsearch-2
  - host: 10.0.1.3
    name: elasticsearch-3


lb_upstreams:
  - name: frontends
    servers:


frontend_upstreams:
  - name: backends
    servers:

