- hosts: "{{ variable_hosts | default('backends') }}"
  remote_user: "{{ remote_user }}"
  become: true
  tasks:
    - name: install open-iscsi
      yum:
        name: [ 'iscsi-initiator-utils' ]
        update_cache: yes
        state: latest

    - name: copy config
      template:
        src: "{{ item }}"
        dest: "/etc/iscsi/{{ item }}"
      loop:
        - iscsid.conf
        - initiatorname.iscsi
      notify:
        - restart iscsi

    - name: connect to target
      shell: |
        iscsiadm -m node -u -T {{ iscsi_iqn_name }}:{{ iscsi_target_name }}
        iscsiadm -m discovery -t st -p {{ iscsi_host }}
        iscsiadm -m node -l -T {{ iscsi_iqn_name }}:{{ iscsi_target_name }}
        iscsiadm -m node -L automatic

    - name: show info get
      shell: iscsiadm -m session -P3
      register: info

    - name: show info iscsi
      debug:
        msg: "{{ info.stdout_lines }}"

  handlers:
    - name: restart iscsi
      systemd:
        name: iscsi
        state: restarted
