- hosts: "{{ variable_hosts | default('backends') }}"
  remote_user: "{{ remote_user }}"
  become: true
  vars:
    app_bgcolors: "{{ ['red', 'green', 'blue', 'white', 'yellow'] | random }}"
  tasks:
    - name: DOCKER | install dnf
      yum:
        name: [ 'dnf-plugins-core', 'dnf' ]

    - name: DOCKER | add dnf repo
      shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: DOCKER | install
      dnf:
        name: ['docker-ce' ]
        update_cache: yes
        state: latest

    - name: DOCKER | start daemon
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: DOCKER | add users
      user:
        name: centos
        groups: docker
        append: yes

    - name: DOCKER | run webdebbuger
      shell: |
        docker rm --force webdebugger
        docker run -d --restart=unless-stopped -e APP_BGCOLOR="{{ app_bgcolors }}" --name webdebugger -p 8080:8080 vscoder/webdebugger:latest

  handlers:
    - name: restart webdebugger
      systemd:
        name: webdebugger
        state: restarted
