- hosts: "{{ variable_hosts | default('elasticsearchs') }}"
  remote_user: "{{ remote_user }}"
  become: true
  vars:
    data_disk_name: /dev/vdb
  tasks:
    - name: ELK-Data | install xfs
      apt:
        name: [ 'xfsprogs' ]
        state: latest
        update_cache: yes

    - name: ELK-Data | Create mount point directory
      file:
        path: "{{ elk_data_dir }}"
        state: directory
        mode: '0755'

    - name: ELK-Data | Format the disk with ext4 filesystem
      filesystem:
        fstype: xfs
        dev: "{{ data_disk_name }}"

    - name: ELK-Data | Mount the disk and add to fstab
      mount:
        path: "{{ elk_data_dir }}"
        src: "{{ data_disk_name }}"
        fstype: xfs
        state: mounted
        opts: defaults
